services:
  example-site:
    container_name: example-site
     image: ghcr.io/boost-creative/docker-wordpress-8:latest
    restart: unless-stopped
    mem_limit: ${WP_MEM_LIMIT:-512m}
    cpus: ${WP_CPU_LIMIT:-2}
    depends_on:
      - example-site-db
    volumes:
      - ./wordpress:/usr/src/wordpress
      - sock:/tmp/sock:ro
    ports:
      - "127.0.0.1:8000:80"
    environment:
      TZ: "America/New_York"
      # DB_HOST: localhost:/tmp/sock/mysqld.sock
      # specify any plugins to install by slug
      # ADDITIONAL_PLUGINS: "better-wp-security simple-cloudflare-turnstile"
      # cron jobs to run from within container 
      # CRON: |
      #   0 * * * * curl http://127.0.0.1/webhook &>/dev/null"
  example-site-db:
    container_name: example-site-mariadb
    image: 'yobasystems/alpine-mariadb:11'
    restart: unless-stopped
    mem_limit: ${WP_MEM_LIMIT:-512m}
    # cpus: ${WP_CPU_LIMIT:-4}
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: ${SERVICE_USER_MARIADB:-wp}
      MYSQL_PASSWORD: ${SERVICE_PASSWORD_MARIADB:-wp}
      MYSQL_ROOT_PASSWORD: ${SERVICE_PASSWORD_MARIADB:-wp}
    volumes:
      - sock:/var/run/mysqld
      - db:/var/lib/mysql
      - ./config/mariadb/my.cnf:/etc/my.cnf
      - ./config/mariadb/db-entrypoint.sh:/scripts/run.sh

volumes:
  db: null
  sock: null
