version: "3"

services:
  # optional
  redis-wp:
    container_name: redis-wp
    image: redis:7-alpine
    restart: unless-stopped

  example-site:
    container_name: example-site
    image: ghcr.io/henrygd/docker-wordpress:latest
    restart: unless-stopped
    volumes:
      - PATH_TO_WORDPRESS_FILES:/usr/src/wordpress
    ports:
      - "127.0.0.1:8000:80"
    environment:
      # installs recommended plugins (see readme)
      INSTALL_PLUGINS: "true"
      # specify any plugins to install by slug
      ADDITIONAL_PLUGINS: "hello-dolly post-smtp"
      # redis host and db (other sites can use dbs up to 15)
      WP_REDIS_HOST: "redis-wp"
      WP_REDIS_DATABASE: 0
      # cron jobs to run from within container (separate lines with \n)
      CRON: "* * * * * touch hello-world \n
        0 * * * * curl http://127.0.0.1/webhook &>/dev/null"
