version: '3'

services:
  example-site:
    container_name: example-site
    image: ghcr.io/boost-creative/docker-wordpress-8:latest
    restart: unless-stopped
    volumes:
      - PATH_TO_WORDPRESS_FILES:/usr/src/wordpress
    ports:
      - '127.0.0.1:8000:80'
    environment:
      TZ: 'America/New_York'
      # specify any plugins to install by slug
      ADDITIONAL_PLUGINS: 'w3-total-cache disable-media-pages'
      # cron jobs to run from within container (separate lines with \n)
      CRON: "* * * * * touch hello-world \n
        0 * * * * curl http://127.0.0.1/webhook &>/dev/null"
