[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/run/supervisord.pid

[program:php-fpm]
command=php-fpm83 -F
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/php83/error.log
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=5
autorestart=false
startretries=0

[program:nginx]
command=nginx -g 'daemon off;'
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/nginx/error.log
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=5
autorestart=false
startretries=0
priority=10

[program:wordpress-nginx-watcher]
command=/usr/local/bin/watch-wordpress-nginx
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true
stopasgroup=true
killasgroup=true
priority=20
